Repository kotlj/Victoria, pull requests merged in 2024-12, with the labels that each got.

#11 stamps
  Resources/Prototypes/Victoria/Stamps.yml
Labels: Changes: No C#

#9 nooc_shattle
  Resources/Maps/Shuttles/ShuttleEvent/nooc_shuttle_lost.yml
  Resources/Prototypes/GameRules/unknown_shuttles.yml
  Resources/Prototypes/Victoria/Noocraty/nooc_shuttles.yml
Labels: Changes: No C#, Changes: Map

#10 crystals
  Resources/Prototypes/Catalog/Cargo/cargo_shuttle.yml
  Resources/Prototypes/Entities/Objects/Devices/Circuitboards/Machine/production.yml
  Resources/Prototypes/Entities/Objects/Materials/ore.yml
  Resources/Prototypes/Entities/Objects/Specific/syndicate.yml
  Resources/Prototypes/Entities/Structures/Machines/lathe.yml
  Resources/Prototypes/Recipes/Lathes/chemistry.yml
  Resources/Prototypes/Recipes/Lathes/devices.yml
  Resources/Prototypes/Recipes/Lathes/tools.yml
  Resources/Prototypes/Victoria/Special_crystals/Special_crystals.yml
  Resources/Textures/Victoria/Special_crystals/bs_crystal.rsi/bs_crystal.png
  Resources/Textures/Victoria/Special_crystals/bs_crystal.rsi/inhand-left.png
  Resources/Textures/Victoria/Special_crystals/bs_crystal.rsi/inhand-right.png
  Resources/Textures/Victoria/Special_crystals/bs_crystal.rsi/meta.json
  Resources/Textures/Victoria/Special_crystals/chrome_crystal.rsi/chrome_crystal.png
  Resources/Textures/Victoria/Special_crystals/chrome_crystal.rsi/inhand-left.png
  Resources/Textures/Victoria/Special_crystals/chrome_crystal.rsi/inhand-right.png
  Resources/Textures/Victoria/Special_crystals/chrome_crystal.rsi/meta.json
  Resources/Textures/Victoria/Special_crystals/cosm_crystal.rsi/cosm_crystal.png
  Resources/Textures/Victoria/Special_crystals/cosm_crystal.rsi/inhand-left.png
  Resources/Textures/Victoria/Special_crystals/cosm_crystal.rsi/inhand-right.png
  Resources/Textures/Victoria/Special_crystals/cosm_crystal.rsi/meta.json
  Resources/Textures/Victoria/Special_crystals/crystal_rock.rsi/bs.png
  Resources/Textures/Victoria/Special_crystals/crystal_rock.rsi/cosm.png
  Resources/Textures/Victoria/Special_crystals/crystal_rock.rsi/meta.json
  Resources/Textures/Victoria/Special_crystals/crystal_rock.rsi/rock.png
  Resources/Textures/Victoria/Special_crystals/crystal_rock.rsi/rock_east.png
  Resources/Textures/Victoria/Special_crystals/crystal_rock.rsi/rock_north.png
  Resources/Textures/Victoria/Special_crystals/crystal_rock.rsi/rock_south.png
  Resources/Textures/Victoria/Special_crystals/crystal_rock.rsi/rock_west.png
  Resources/Textures/Victoria/Special_crystals/crystal_rock.rsi/rs.png
  Resources/Textures/Victoria/Special_crystals/module.rsi/bs_module.png
  Resources/Textures/Victoria/Special_crystals/module.rsi/cosm_core.png
  Resources/Textures/Victoria/Special_crystals/module.rsi/meta.json
  Resources/Textures/Victoria/Special_crystals/module.rsi/rs_module.png
  Resources/Textures/Victoria/Special_crystals/sap_crystal.rsi/inhand-left.png
  Resources/Textures/Victoria/Special_crystals/sap_crystal.rsi/inhand-right.png
  Resources/Textures/Victoria/Special_crystals/sap_crystal.rsi/meta.json
  Resources/Textures/Victoria/Special_crystals/sap_crystal.rsi/sap_crystal.png
  Resources/Textures/Victoria/Special_crystals/si_crystal.rsi/inhand-left.png
  Resources/Textures/Victoria/Special_crystals/si_crystal.rsi/inhand-right.png
  Resources/Textures/Victoria/Special_crystals/si_crystal.rsi/meta.json
  Resources/Textures/Victoria/Special_crystals/si_crystal.rsi/si_crystal.png
  Resources/Textures/Victoria/Special_crystals/transmutator.rsi/building.png
  Resources/Textures/Victoria/Special_crystals/transmutator.rsi/icon.png
  Resources/Textures/Victoria/Special_crystals/transmutator.rsi/inserting.png
  Resources/Textures/Victoria/Special_crystals/transmutator.rsi/meta.json
  Resources/Textures/Victoria/Special_crystals/transmutator.rsi/panel.png
  Resources/Textures/Victoria/Special_crystals/transmutator.rsi/unlit-building.png
  Resources/Textures/Victoria/Special_crystals/transmutator.rsi/unlit.png
Labels: Changes: No C#, Changes: Sprites

#15 salvage
  Resources/Maps/Ruins/corvax_accident.yml
  Resources/Maps/Ruins/corvax_gas_station.yml
  Resources/Maps/Ruins/corvax_hotel_trivago.yml
  Resources/Maps/Ruins/corvax_ore.yml
  Resources/Maps/Ruins/corvax_rnd_debris.yml
  Resources/Maps/Ruins/corvax_sanctus.yml
  Resources/Maps/Ruins/corvax_syndi_base.yml
  Resources/Maps/Ruins/corvax_ussp_asteroid.yml
  Resources/Maps/Salvage/engineering-chunk.yml
  Resources/Maps/Salvage/medium-crashed-shuttle.yml
  Resources/Maps/Salvage/ruin-cargo-salvage.yml
  Resources/Maps/Salvage/small-a-1.yml
  Resources/Maps/Salvage/tick-colony.yml
  Resources/Maps/Salvage/victoria-broken-shattle-kmlg.yml
  Resources/Maps/Salvage/victoria-house-snk.yml
  Resources/Maps/Salvage/victoria-salvage-asteroid.yml
  Resources/Prototypes/Maps/salvage.yml
Labels: Changes: No C#, Changes: Map

#16 Update CDN url in update script
  Tools/publish_multi_request.py
Labels: Changes: No C#

#18 disable auto-publish publish.yml
  .github/workflows/publish.yml
Labels: Changes: No C#
