Repository kotlj/Victoria, pull requests merged in 2025-01, with the labels that each got.

#21 goals
  Resources/Locale/ru-RU/victoria/station-goal/station-goal-component.ftl
  Resources/Prototypes/Entities/Stations/nanotrasen.yml
  Resources/Prototypes/Victoria/Stations/base.yml
  Resources/Prototypes/Victoria/Stations/goals.yml
Labels: Changes: No C#, Changes: Localization, S: Untriaged, size/L

#25 names
  Resources/Locale/ru-RU/tips.ftl
  Resources/Prototypes/Datasets/Names/diona.yml
  Resources/Prototypes/Datasets/Names/moth_first_female.yml
  Resources/Prototypes/Datasets/Names/moth_first_male.yml
  Resources/Prototypes/Datasets/Names/moth_last.yml
  Resources/Prototypes/Entities/Objects/Materials/Sheets/glass.yml
  Resources/Prototypes/Victoria/Electron/RawCircuitBord.yml
  Resources/Prototypes/Victoria/Special_crystals/Special_crystals.yml
  Resources/Prototypes/Victoria/Toxi/Toxi.yml
Labels: Changes: No C#, Changes: Localization, S: Untriaged, size/XL

#24 bfix
  Resources/Maps/claw_station.yml
  Resources/Maps/cross_station.yml
  Resources/Maps/victoria_scc.yml
  Resources/Prototypes/Entities/Objects/Materials/ore.yml
  Resources/Prototypes/Entities/Stations/base.yml
  Resources/Prototypes/Maps/victoria_scc.yml
  Resources/Prototypes/Recipes/Lathes/sheet.yml
  Resources/Prototypes/Victoria/Electron/ComponentsCircuitBord.yml
  Resources/Prototypes/Victoria/Electron/RawCircuitBord.yml
  Resources/Prototypes/Victoria/Electron/RawMatElectronics.yml
  Resources/Prototypes/Victoria/Special_crystals/Special_crystals.yml
  Resources/Prototypes/Victoria/Toxi/Toxi_enemy.yml
  Resources/Prototypes/Victoria/Umpor/umpor.yml
Labels: Changes: No C#, Changes: Map, S: Untriaged, size/XL

#27 Återbalansera
  Resources/Prototypes/GameRules/events.yml
  Resources/Prototypes/GameRules/meteorswarms.yml
  Resources/Prototypes/GameRules/unknown_shuttles.yml
Labels: Changes: No C#, S: Untriaged, size/M

#28 Update manifest.yml
  Resources/manifest.yml
Labels: Changes: No C#, S: Untriaged

#29 Config upd
  Resources/ConfigPresets/Victoria/victoria.toml
  Resources/Prototypes/Victoria/Guidebook/rules.yml
  Resources/ServerInfo/Victoria/ServerRules/MrpRuleset.xml
  Resources/ServerInfo/Victoria/ServerRules/PunishmentTypes.xml
  Resources/ServerInfo/Victoria/ServerRules/Rule0.1.xml
  Resources/ServerInfo/Victoria/ServerRules/Rule0.2.xml
  Resources/ServerInfo/Victoria/ServerRules/Rule0.3.xml
  Resources/ServerInfo/Victoria/ServerRules/Rule0.4.xml
  Resources/ServerInfo/Victoria/ServerRules/Rule0.5.xml
  Resources/ServerInfo/Victoria/ServerRules/Rule0.xml
  Resources/ServerInfo/Victoria/ServerRules/Rule1.1.xml
  Resources/ServerInfo/Victoria/ServerRules/Rule1.2.xml
  Resources/ServerInfo/Victoria/ServerRules/Rule1.xml
  Resources/ServerInfo/Victoria/ServerRules/Rule2.1.xml
  Resources/ServerInfo/Victoria/ServerRules/Rule2.2.xml
  Resources/ServerInfo/Victoria/ServerRules/Rule2.3.xml
  Resources/ServerInfo/Victoria/ServerRules/Rule2.4.xml
  Resources/ServerInfo/Victoria/ServerRules/Rule2.5.xml
  Resources/ServerInfo/Victoria/ServerRules/Rule2.6.1.xml
  Resources/ServerInfo/Victoria/ServerRules/Rule2.6.2.xml
  Resources/ServerInfo/Victoria/ServerRules/Rule2.6.3.xml
  Resources/ServerInfo/Victoria/ServerRules/Rule2.6.4.xml
  Resources/ServerInfo/Victoria/ServerRules/Rule2.6.5.xml
  Resources/ServerInfo/Victoria/ServerRules/Rule2.6.xml
  Resources/ServerInfo/Victoria/ServerRules/Rule2.7.xml
  Resources/ServerInfo/Victoria/ServerRules/Rule2.8.xml
  Resources/ServerInfo/Victoria/ServerRules/Rule2.xml
  Resources/ServerInfo/Victoria/ServerRules/Rule3.1.xml
  Resources/ServerInfo/Victoria/ServerRules/Rule3.2.xml
  Resources/ServerInfo/Victoria/ServerRules/Rule3.3.xml
  Resources/ServerInfo/Victoria/ServerRules/Rule3.4.xml
  Resources/ServerInfo/Victoria/ServerRules/Rule3.5.xml
  Resources/ServerInfo/Victoria/ServerRules/Rule3.6.xml
  Resources/ServerInfo/Victoria/ServerRules/Rule3.xml
  Resources/ServerInfo/Victoria/ServerRules/Rule4.1.xml
  Resources/ServerInfo/Victoria/ServerRules/Rule4.2.xml
  Resources/ServerInfo/Victoria/ServerRules/Rule4.3.xml
  Resources/ServerInfo/Victoria/ServerRules/Rule4.4.xml
  Resources/ServerInfo/Victoria/ServerRules/Rule4.xml
  Resources/ServerInfo/Victoria/ServerRules/Rule5.1.xml
  Resources/ServerInfo/Victoria/ServerRules/Rule5.2.xml
  Resources/ServerInfo/Victoria/ServerRules/Rule5.3.xml
  Resources/ServerInfo/Victoria/ServerRules/Rule5.4.xml
  Resources/ServerInfo/Victoria/ServerRules/Rule5.xml
  Resources/ServerInfo/Victoria/ServerRules/Rule6.1.xml
  Resources/ServerInfo/Victoria/ServerRules/Rule6.2.xml
  Resources/ServerInfo/Victoria/ServerRules/Rule6.xml
Labels: Changes: No C#, S: Untriaged

#30 Update victoria.toml
  Resources/ConfigPresets/Victoria/victoria.toml
Labels: Changes: No C#, S: Untriaged, size/XS

#32 Plumbum
  Resources/Prototypes/Entities/Objects/Materials/ingots.yml
  Resources/Prototypes/Entities/Structures/Doors/MaterialDoors/material_doors.yml
  Resources/Prototypes/Entities/Structures/Machines/lathe.yml
  Resources/Prototypes/Entities/Structures/Walls/asteroid.yml
  Resources/Prototypes/Entities/Structures/Walls/walls.yml
  Resources/Prototypes/Entities/Structures/Windows/clockwork.yml
  Resources/Prototypes/Entities/Structures/Windows/mining.yml
  Resources/Prototypes/Entities/Structures/Windows/plasma.yml
  Resources/Prototypes/Entities/Structures/Windows/plastitanium.yml
  Resources/Prototypes/Entities/Structures/Windows/reinforced.yml
  Resources/Prototypes/Entities/Structures/Windows/rplasma.yml
  Resources/Prototypes/Entities/Structures/Windows/ruranium.yml
  Resources/Prototypes/Entities/Structures/Windows/shuttle.yml
  Resources/Prototypes/Entities/Structures/Windows/uranium.yml
  Resources/Prototypes/Recipes/Construction/Graphs/structures/girder.yml
  Resources/Prototypes/Recipes/Construction/Graphs/structures/windowdirectional.yml
  Resources/Prototypes/Recipes/Lathes/security.yml
  Resources/Prototypes/Recipes/Lathes/sheet.yml
  Resources/Prototypes/Victoria/Electron/ComponentsCircuitBord.yml
  Resources/Prototypes/Victoria/Electron/RawCircuitBord.yml
  Resources/Prototypes/Victoria/Plumbum/plumbum.yml
  Resources/Prototypes/Victoria/Special_crystals/Special_crystals.yml
  Resources/Prototypes/Victoria/Toxi/Toxi_enemy.yml
  Resources/Textures/Victoria/Electron/ore_electronic.rsi/meta.json
  Resources/Textures/Victoria/Electron/ore_electronic.rsi/plumbum.png
  Resources/Textures/Victoria/Plumbum/plumbum_sheet.rsi/meta.json
  Resources/Textures/Victoria/Plumbum/plumbum_sheet.rsi/plumbum-inhand-left.png
  Resources/Textures/Victoria/Plumbum/plumbum_sheet.rsi/plumbum-inhand-right.png
  Resources/Textures/Victoria/Plumbum/plumbum_sheet.rsi/plumbum.png
  Resources/Textures/Victoria/Plumbum/plumbum_sheet.rsi/plumbum_2.png
  Resources/Textures/Victoria/Plumbum/plumbum_sheet.rsi/plumbum_3.png
  Resources/Textures/Victoria/Plumbum/plumbum_wall.rsi/full.png
  Resources/Textures/Victoria/Plumbum/plumbum_wall.rsi/meta.json
  Resources/Textures/Victoria/Plumbum/plumbum_wall.rsi/solid0.png
  Resources/Textures/Victoria/Plumbum/plumbum_wall.rsi/solid1.png
  Resources/Textures/Victoria/Plumbum/plumbum_wall.rsi/solid2.png
  Resources/Textures/Victoria/Plumbum/plumbum_wall.rsi/solid3.png
  Resources/Textures/Victoria/Plumbum/plumbum_wall.rsi/solid4.png
  Resources/Textures/Victoria/Plumbum/plumbum_wall.rsi/solid5.png
  Resources/Textures/Victoria/Plumbum/plumbum_wall.rsi/solid6.png
  Resources/Textures/Victoria/Plumbum/plumbum_wall.rsi/solid7.png
  Resources/Textures/Victoria/Plumbum/plumbum_wall.rsi/wall_girder.png
  Resources/Textures/Victoria/Plumbum/plumbum_wall_dir.rsi/meta.json
  Resources/Textures/Victoria/Plumbum/plumbum_wall_dir.rsi/plumbum.png
Labels: Changes: No C#, Changes: Sprites, S: Untriaged, size/L

#33 lb_1
  Resources/Prototypes/Catalog/Fills/Books/bookshelf.yml
  Resources/Prototypes/Victoria/LearnBook/LearnBooks.yml
  Resources/Textures/Victoria/Objects/Misc/books.rsi/book_BaseElectro.png
  Resources/Textures/Victoria/Objects/Misc/books.rsi/book_BookLogicToxy.png
  Resources/Textures/Victoria/Objects/Misc/books.rsi/book_BookMaterialsScience2.png
  Resources/Textures/Victoria/Objects/Misc/books.rsi/book_CookingBase.png
  Resources/Textures/Victoria/Objects/Misc/books.rsi/book_DrinksBase.png
  Resources/Textures/Victoria/Objects/Misc/books.rsi/book_KorpKodex.png
  Resources/Textures/Victoria/Objects/Misc/books.rsi/book_LE.png
  Resources/Textures/Victoria/Objects/Misc/books.rsi/book_MedOsn.png
  Resources/Textures/Victoria/Objects/Misc/books.rsi/book_Robototech.png
  Resources/Textures/Victoria/Objects/Misc/books.rsi/book_SingElectro.png
  Resources/Textures/Victoria/Objects/Misc/books.rsi/book_TeslaElectro.png
  Resources/Textures/Victoria/Objects/Misc/books.rsi/meta.json
  Resources/Textures/Victoria/Objects/Misc/chest.rsi/base.png
  Resources/Textures/Victoria/Objects/Misc/chest.rsi/closed.png
  Resources/Textures/Victoria/Objects/Misc/chest.rsi/icon.png
  Resources/Textures/Victoria/Objects/Misc/chest.rsi/meta.json
  Resources/Textures/Victoria/Objects/Misc/chest.rsi/open.png
  Resources/Textures/Victoria/Objects/Misc/chest.rsi/sparking.png
  Resources/Textures/Victoria/Objects/Misc/chest.rsi/welded.png
Labels: Changes: No C#, Changes: Sprites, S: Untriaged, size/L

#34 Fix rules minor errors
  Resources/Prototypes/Entities/Structures/Walls/walls.yml
  Resources/Prototypes/Recipes/Construction/Graphs/structures/windowdirectional.yml
  Resources/Prototypes/Victoria/Guidebook/rules.yml
  Resources/Prototypes/Victoria/Plumbum/plumbum.yml
  Resources/ServerInfo/Victoria/Guidebook/ServerRules/MrpRuleset.xml
  Resources/ServerInfo/Victoria/Guidebook/ServerRules/PunishmentTypes.xml
  Resources/ServerInfo/Victoria/Guidebook/ServerRules/Rule0.1.xml
  Resources/ServerInfo/Victoria/Guidebook/ServerRules/Rule0.2.xml
  Resources/ServerInfo/Victoria/Guidebook/ServerRules/Rule0.3.xml
  Resources/ServerInfo/Victoria/Guidebook/ServerRules/Rule0.4.xml
  Resources/ServerInfo/Victoria/Guidebook/ServerRules/Rule0.5.xml
  Resources/ServerInfo/Victoria/Guidebook/ServerRules/Rule0.xml
  Resources/ServerInfo/Victoria/Guidebook/ServerRules/Rule1.1.xml
  Resources/ServerInfo/Victoria/Guidebook/ServerRules/Rule1.2.xml
  Resources/ServerInfo/Victoria/Guidebook/ServerRules/Rule1.xml
  Resources/ServerInfo/Victoria/Guidebook/ServerRules/Rule2.1.xml
  Resources/ServerInfo/Victoria/Guidebook/ServerRules/Rule2.2.xml
  Resources/ServerInfo/Victoria/Guidebook/ServerRules/Rule2.3.xml
  Resources/ServerInfo/Victoria/Guidebook/ServerRules/Rule2.4.xml
  Resources/ServerInfo/Victoria/Guidebook/ServerRules/Rule2.5.xml
  Resources/ServerInfo/Victoria/Guidebook/ServerRules/Rule2.6.1.xml
  Resources/ServerInfo/Victoria/Guidebook/ServerRules/Rule2.6.2.xml
  Resources/ServerInfo/Victoria/Guidebook/ServerRules/Rule2.6.3.xml
  Resources/ServerInfo/Victoria/Guidebook/ServerRules/Rule2.6.4.xml
  Resources/ServerInfo/Victoria/Guidebook/ServerRules/Rule2.6.5.xml
  Resources/ServerInfo/Victoria/Guidebook/ServerRules/Rule2.6.xml
  Resources/ServerInfo/Victoria/Guidebook/ServerRules/Rule2.7.xml
  Resources/ServerInfo/Victoria/Guidebook/ServerRules/Rule2.8.xml
  Resources/ServerInfo/Victoria/Guidebook/ServerRules/Rule2.xml
  Resources/ServerInfo/Victoria/Guidebook/ServerRules/Rule3.1.xml
  Resources/ServerInfo/Victoria/Guidebook/ServerRules/Rule3.2.xml
  Resources/ServerInfo/Victoria/Guidebook/ServerRules/Rule3.3.xml
  Resources/ServerInfo/Victoria/Guidebook/ServerRules/Rule3.4.xml
  Resources/ServerInfo/Victoria/Guidebook/ServerRules/Rule3.5.xml
  Resources/ServerInfo/Victoria/Guidebook/ServerRules/Rule3.6.xml
  Resources/ServerInfo/Victoria/Guidebook/ServerRules/Rule3.xml
  Resources/ServerInfo/Victoria/Guidebook/ServerRules/Rule4.1.xml
  Resources/ServerInfo/Victoria/Guidebook/ServerRules/Rule4.2.xml
  Resources/ServerInfo/Victoria/Guidebook/ServerRules/Rule4.3.xml
  Resources/ServerInfo/Victoria/Guidebook/ServerRules/Rule4.4.xml
  Resources/ServerInfo/Victoria/Guidebook/ServerRules/Rule4.xml
  Resources/ServerInfo/Victoria/Guidebook/ServerRules/Rule5.1.xml
  Resources/ServerInfo/Victoria/Guidebook/ServerRules/Rule5.2.xml
  Resources/ServerInfo/Victoria/Guidebook/ServerRules/Rule5.3.xml
  Resources/ServerInfo/Victoria/Guidebook/ServerRules/Rule5.4.xml
  Resources/ServerInfo/Victoria/Guidebook/ServerRules/Rule5.xml
  Resources/ServerInfo/Victoria/Guidebook/ServerRules/Rule6.1.xml
  Resources/ServerInfo/Victoria/Guidebook/ServerRules/Rule6.2.xml
  Resources/ServerInfo/Victoria/Guidebook/ServerRules/Rule6.xml
Labels: Changes: No C#, S: Untriaged, size/L

#36 move circuitfloor
  Resources/Prototypes/Entities/Structures/Machines/lathe.yml
Labels: Changes: No C#, S: Untriaged, size/XS
